version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: agriweather-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agriweather_db
      MYSQL_USER: agriuser
      MYSQL_PASSWORD: agripass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/agriweather.sql:/docker-entrypoint-initdb.d/agriweather.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "agriuser",
          "-pagripass",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: agriweather-ai-service
    restart: always
    ports:
      - "8001:8001"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agriweather-backend
    restart: always
    depends_on:
      mysql-db:
        condition: service_healthy
      ai-service:
        condition: service_started
    environment:
      DATABASE_URL: mysql+pymysql://agriuser:agripass@mysql-db:3306/agriweather_db
      AI_SERVICE_URL: http://ai-service:8001
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agriweather-frontend
    restart: always
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "5173:5173"

volumes:
  mysql_data:
